### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 1

### ISSUE THREAD

**Issue by smar000** [Evsdd/Evohome_Schedule_Backup#1]
Hi Dan

I was just trying out your backup script with an arduino/cc1101 based clone. Unfortunately I keep getting the following error:

```
Traceback (most recent call last):
  File "./evobackup.py", line 133, in <module>
    response = msg_send_back(msg_type='RQ', msg_addr1=GatewayTXT, msg_addr2=ControllerTXT, msg_comm=Com_SCHD, msg_pay=payload,msg_delay=0,msg_resp=1)
  File "./evobackup.py", line 75, in msg_send_back
    data = ComPort.readline().decode().replace("\x11","").rstrip() # Wait and read data
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 1: invalid start byte

```

I haven't had a chance to spend any time on it, but was wondering if you had come across this, or know off-hand what the fix might be.

Thanks.

**Comment by Evsdd** [comment]
Hi,

No, I don’t think I’ve encountered this error, but my guess is that it’s a difference between the characters returned by the clone firmware you’re using versus the HGI80 which I think I was using.  The HGI80 add loads of x11 control characters and I had to strip these out in the code, but it looks like it might be rejecting one of the error strings that some of the firmwares print out.  Which firmware are you using as I’m happy to see what happens and if I can add a tweak to the code to fix it?

Regards,
Dan

**Comment by smar000** [comment]
Thanks for the quick reply.

I'm using the fifo branch from ghoti57's repo (https://github.com/ghoti57/evofw2/tree/fifo), though on a slightly older build (I see that he has recently updated this build to include rssi data, which I haven't tried yet).

**Comment by Evsdd** [comment]
I managed to recreate the error which can be caused if the wrong baud rate is set and hence the serial port is filled with junk non-ASCII characters.  Can you double-check your baud rate settings to make sure they match your firmware and re-test?  I was able to successfully test with both a HGI80 and an RFBee (using the EvohomeWirelessFW firmware).  Unfortunately, I wasn't able to successfully test with the exact firmware you're using as I couldn't get it to reliably send and receive.

**Comment by smar000** [comment]
You are of course absolutely correct - I had forgetten to correct the baud rate as I had dropped it down to 76.8. Sorry for wasting your time on that.

Unfortunately it is still struggling as the received `data` length seems to be too short, e.g.:

```
ControllerID=0x02227D (00:139901)
Send:[RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 04:001048 --:------ 04:001048 30C9 003 0008D8
Re-send[1][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 01:139901 --:------ 01:139901 1F09 003 FF05C3
Re-send[2][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
---  I --- 01:139901 --:------ 01:139901 2309 036 0001F401092E0208CA0301F40401F40501F40602260701F40808FC0906400A01F40B01F4
---  I --- 01:139901 RQ --:------ --- 18001:139901 0730C9 000:13030 99001--:--08-- DC030080 007 7F00042000080080006705
084406090A07095D0808D80909440A09790B091B

Traceback (most recent call last):
  File "./evobackup.py", line 133, in <module>
    response = msg_send_back(msg_type='RQ', msg_addr1=GatewayTXT, msg_addr2=ControllerTXT, msg_comm=Com_SCHD, msg_pay=payload,msg_delay=0,msg_resp=1)
  File "./evobackup.py", line 83, in msg_send_back
    RP_zone = int(data[51:52], 16) # Extract first 2 bytes of payload and convert to int
ValueError: invalid literal for int() with base 16: ''
```

I've tried running a number of times, and get different `data` values, e.g.  but no successful send:

```
Re-send[3][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
---  I --- 01:139901 --:------ 01:139901 2309 036 0001F401092E0208CA0301F40401F40501F40602260701F40808FC0906400A01F40B01F4
---  I --- 01:139901 --:------ 01:139901 30C9 030 0008C703086C0408540508RQ 44--06180008730 0F7070:13099901 5D-08:--- 080404 D80909007 4400200080A00009
760B091A
```

I suspect the issue maybe with the firmware and/or hardware, though the combination seems to be working well when I use it for listening/sending via the evolistener script.

Thanks again.

**Comment by Evsdd** [comment]
Hi,
Thanks for the additional information.  It looks like you're seeing the same issue that I was having when I tested the code using various versions of the evofw2-fifo firmware.  For some reason either the code or the firmware aren't picking up the RP message which immediately follows the RQ.  Unfortunately, when I tried to test this directly using a serial terminal the firmware seemed to lock-up so I was unable to test further (this obviously isn't happening in your case as further messages are picked up by the code).  I'll try and find a working version of the firmware and troubleshoot further as I can see that there's also message corruption (concatenation) which eventually triggers the error.  Even without this message corruption, as the code can't detect the RP 0404 to the specific RQ 0404, it will just continue to try 5 times for each zone and then exit.

**Comment by smar000** [comment]
Hi Dan

Thanks for that. I actually did get a successful send a couple of times, but even then, various errors continued, as it looks as if the received/decoded data lengths are too short - again pointing to hardware/firmware issues.

**Comment by Evsdd** [comment]
I've pushed a version of the EvohomeWirelessFW firmware for the NanoCUL (Nano branch) and tested this successfully with the schedule backup code.  The problem seemed to be with the other firmwares which didn't either reliably send the RQ message or pick up the RP response.  Please let me know how you get on if you give it a try.

**Comment by smar000** [comment]
Thanks for looking into this. 

I still seem to be struggling with the send/receive, even with the Nano branch from your repo, e.g.:

```
ControllerID=0x051D74 (01:073076)
Send:[RQ --- 18:000730 01:073076 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:073076 --:------ 0404 007 00200008000100
---  I --- 04:227952 --:------ 01:139901 3150 002 015C
Re-send[1][RQ --- 18:000730 01:073076 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:073076 --:------ 0404 007 00200008000100
---  I --- 34:015243 --:------ 34:015243 30C9 003 0008EE
Re-send[2][RQ --- 18:000730 01:073076 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:073076 --:------ 0404 007 00200008000100
---  I --- 04:143924 --:------ 04:143924 30C9 003 000846
Re-send[3][RQ --- 18:000730 01:073076 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:073076 --:------ 0404 007 00200008000100
---  I --- 07:043555 --:------ 07:043555 1260 003 0011B9
---  I --- 01:139901 --:------ 01:139901 3150 002 FC74
Re-send[4][RQ --- 18:000730 01:073076 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:073076 --:------ 0404 007 00200008000100
---  I --- 34:112193 --:------ 34:112193 30C9 003 0008F9
Re-send[5][RQ --- 18:000730 01:073076 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:073076 --:------ 0404 007 00200008000100
Send failure!
```
I've tried changing the baud rates to 76k8 and 250k as well (as I recall in the past there were some issues with transmitting at 115k), but that didn't resolve the issue either.

Unfortunately I don't know enough about how the CC1101 works/is wired. Is it possible that I have my pins incorrectly defined in the firmware? The configuration parameters in my 'working' firmware (ghoti57 fifo branch) are:

```
// Connection to CC1101 GDO2
#define GDO2_CLK_PIN         2
#define GDO2_CLK_INT         INT0
#define GDO2_CLK_INTVECT     INT0_vect
#define GDO2_CLK_INT_ISCn0   ISC00
#define GDO2_CLK_INT_ISCn1   ISC01

// Connection to CC1101 GDO0
#define GDO0_INT         INT1
#define GDO0_INTVECT     INT1_vect
#define GDO0_INT_ISCn0   ISC10
#define GDO0_INT_ISCn1   ISC11

#define GDO0_DATA_DDR     DDRD
#define GDO0_DATA_PORT    PORTD
#define GDO0_DATA_PIN     3
#define GDO0_DATA_IN      PIND
```

Do these match with the defintions in your .ino file (I am not quite clear as to what GDO0_PD and GDO2_PD are supposed to connect to)? 
```
#define GDO0_INT 1 // INT0(PD2) wired to GDO0 on CC1101
#define GDO2_INT 0 // INT1(PD3) wired to GDO2 on CC1101 (CCx_IOCFG2==0x0B Serial Clock. Synchronous to the data in synchronous serial mode. In RX mode, data is set up on the falling edge by CC1101 when GDOx_INV=0. In TX mode, data is sampled by CC1101 on the rising edge of the serial clock when GDOx_INV=0.)

#define GDO0_PD 8 // PD2(INT0) wired to GDO0 on CC1101 (CCx_IOCFG0==0x0C Serial Synchronous Data Output. Used for synchronous serial mode.)
#define GDO2_PD 4 // PD3(INT1) wired to GDO2 on CC1101

```
As a test I did try changing GDO0_PD to 3 and GDO2_PD to 2, but then the firmware stopped receiving altogether.

**Comment by Evsdd** [comment]
Thanks for persevering with this, I think you're very close to get it working.  You shouldn't need to mess with any of the pin definitions if your arduino nano+cc1101 works with the ghoti57/evofw2-fifo firmware.  I think I've spotted one problem with the first section of the output.  You need to set the ControllerID to your controller which will be the encoded version of '01:139901'.  You can get this from your controller GUI, if you don't already have the info.  Once you've set this correctly the RPs should start to appear following each RQ.  If this does work, you might also find that the ghoti57 firmware also works, but I wasn't able to get it working myself with this script for some reason.  Good luck!

**Comment by smar000** [comment]
Thank you for all your efforts and bearing with me on this.  I've corrected the controller ID now, but still seem to be having the same sort of issues as before. Most of the time I get the failed to send, but I did manage to t get the following on one occasion:

```
ControllerID=0x02227D (00:139901)
Send:[RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 34:214769 --:------ 34:214769 30C9 003 00090F
Re-send[1][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 01:139901 --:------ 01:139901 1F09 003 FF05C3
Re-send[2][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
---  I --- 01:139901 RQ--:------  --- 18:001:139901 0000A 0730 048 000:391 10--:--01F4---- 0D0404 AC0 0001200000080001F4010D00
Traceback (most recent call last):
  File "./evo_schedule_backup_v0.3.py", line 135, in <module>
    response = msg_send_back(msg_type='RQ', msg_addr1=GatewayTXT, msg_addr2=ControllerTXT, msg_comm=Com_SCHD, msg_pay=payload,msg_delay=0,msg_resp=1)
  File "./evo_schedule_backup_v0.3.py", line 83, in msg_send_back
    RP_zone = int(data[51:52], 16) # Extract first 2 bytes of payload and convert to int

```
And other times:
```
ControllerID=0x02227D (00:139901)
Send:[RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 04:228042 --:------ 01:139901 3150 002 0200
Re-send[1][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 04:228048 --:------ 01:139901 12B0 003 050000
Re-send[2][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 04:228048 --:------ 01:139901 12B0 003 050000
Re-send[3][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 34:112193 --:------ 34:112193 30C9 003 000937
Re-send[4][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
---  I --- 13:127198 --:------ 13:127198 3EF0 003 00C8FF
Re-send[5][RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 00:139901 --:------ 0404 007 00200008000100
Send failure!
```
Any other ideas?

**Comment by Evsdd** [comment]
So close!  There's a typo in your ControllerID.  I calculate it to be 0x6227D not 0x2227D.  This should produce 01:139901 as the 2nd deviceID in the RQ.  At the moment it translates to 00:139901 which will just be ignored by your controller.  Give that a try and I'll keep my fingers crossed!

**Comment by smar000** [comment]
Argh! That's what happens you rush things last thing in the evening :)

I corrected the controller ID, but still no joy (same constant resending messages). To eliminate hardware as an issue, I put together another arduino/cc1101, but same problem:

```
ControllerID=0x06227D (01:139901)
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
# EvohomeWirelessFW v0.8 Copyright (c) 2015 Hydrogenetic
# Licensed under GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
--- RQ --- 18:056026 01:139901 --:------ 0404 007 00200008000100
---  I --- 04:228042 --:------ 04:228042 30C9 003 0007C7
Re-send[1][RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 00200008000100
---  I --- 04:143926 --:------ 04:143926 30C9 003 000C87
Re-send[2][RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 00200008000100
---  I --- 04:001048 --:------ 04:001048 30C9 003 000968
Re-send[3][RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 00200008000100
---  I --- 01:139901 --:------ 01:139901 1F09 003 FF05C3
Re-send[4][RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
---  I --- 01:139901 --:------ 01:139901 2309 036 00092E0107D00207080301F40401F40508340609920709600807D00907080A09920B0834
--- RQ --- 18:056026 01:139901 --:------ 0404 007 00200008000100
---  I --- 04:228096 --:------ 04:228096 30C9 003 0008C7
Re-send[5][RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 00200008000100
Send failure!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 01200008000100
---  I --- 34:112193 --:------ 34:112193 30C9 003 000933
Re-send[1][RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 01200008000100
---  I --- 34:015243 --:------ 34:015243 30C9 003 000912
Re-send[2][RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 01200008000100
---  I --- 34:015243 --:------ 34:015243 2309 003 0008FC
Re-send[3][RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 01200008000100
---  I --- 13:127198 --:------ 13:127198 3EF0 003 00C8FF
Re-send[4][RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000100]
--- RQ --- 18:056026 01:139901 --:------ 0404 007 01200008000100
---  I --- 13:127198 --:------ 13:127198 3B00 002 00C8
---  I --- 13:102710 --:------ 13:102710 3EF0 003 0000FF
---  I --- 13:133904 --:------ 13:133904 3EF0 003 0000FF
---  I --- *INCOMPLETE*
Traceback (most recent call last):
  File "./evo_schedule_backup_v0.3.py", line 135, in <module>
    response = msg_send_back(msg_type='RQ', msg_addr1=GatewayTXT, msg_addr2=ControllerTXT, msg_comm=Com_SCHD, msg_pay=payload,msg_delay=0,msg_resp=1)
  File "./evo_schedule_backup_v0.3.py", line 83, in msg_send_back
    RP_zone = int(data[51:52], 16) # Extract first 2 bytes of payload and convert to int
ValueError: invalid literal for int() with base 16: ''
```


Reverted back to the fifo firmware on this new arduino, and bingo I am getting "Send success" messages! However, this is still failing at the end.


```
ControllerID=0x06227D (01:139901)
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100
---  I --- 04:227952 --:------ 01:139901 3150 002 0100
Re-send[1][RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100]
RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000100
--- RP --- 01:139901 18:056026 --:------ 0404 048 0020000829010568816DD13D0EC2300C05E097BFD28A810B2094135419D9A93808E20C485C8F918913700A460694BAD8
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000205]
RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000205
--- RP --- 01:139901 18:056026 --:------ 0404 048 00200008290205719A6C7972FCC90E20E7618071803A170B3C7B9DBD5DCE92CA8E1EF8567587007CCCCEFCEF868D2996
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000305]
RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000305
--- RP --- 01:139901 18:056026 --:------ 0404 048 002000082903051919D2CFB0019591D1ABB764489D6523A98C8C7B2CB3DAB08D396CC3706C483F87F5AE5CC3706C74EA
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000405]
RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000405
--- RP --- 01:139901 18:056026 --:------ 0404 048 002000082904052D19B27C8FF57FF886E1D9907E9E8DA4EAAEB3B1E5BAB018AF8DF4CBD9DEE62CA9EC36BBF2976131C6
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000505]
RQ --- 18:000730 01:139901 --:------ 0404 007 00200008000505
--- RP --- 01:139901 18:056026 --:------ 0404 035 002000081C050521A87EE76A575DC3E8D8D01919A758663487CE685753FC01A24C3031
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000100]
RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000100
--- RP --- 01:139901 18:056026 --:------ 0404 048 0120000829010668816DD0B10DC2301040D13B3B36892868182013208B15408C404195828205E8190151310083300225
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000206]
RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000206
--- RP --- 01:139901 18:056026 --:------ 0404 048 012000082902068344D4F862E792B32E45E47C9DF364030020A4E712178F26ADC7F68A8BCF42B6B7A51644FB56009B62
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000306]
RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000306
--- RP --- 01:139901 18:056026 --:------ 0404 048 01200008290306EFD601F4B8C2B1A162A062201BB225A36EE72D19D39CC9C6AF09A29586510CA39CC32886E5735CDB79
Send success!
Send:[RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000406]
RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000406
--- RP --- 01:139901 18:056026 --:------ 0404 048 012000082904062B0DAB18960D2FF626A3E1B94AB9AB4A31A875F1F5ACA7FF515B3B3282983B0DC692	*ERR_MANCHESTER_ENCODING*
--- RP --- 56:141276 56:238235 --:------ 	*ERR_UNKNOWN*
---  I --- 01:139901 --:------ 01:139901 1F09 003 FF05C3
Re-send[1][RQ --- 18:000730 01:139901 --:------ 0404 007 01200008000406]
---  I --- 01:139901 --:------ 01:139901 2309 036 R00Q --- 0918:02E010073070 D01139021 --:07-----0803- 04010407F4 104000080010040F4056
08340609920709600807D00907080A09920B0834
Traceback (most recent call last):
  File "./evo_schedule_backup_v0.3.py", line 135, in <module>
    response = msg_send_back(msg_type='RQ', msg_addr1=GatewayTXT, msg_addr2=ControllerTXT, msg_comm=Com_SCHD, msg_pay=payload,msg_delay=0,msg_resp=1)
  File "./evo_schedule_backup_v0.3.py", line 83, in msg_send_back
    RP_zone = int(data[51:52], 16) # Extract first 2 bytes of payload and convert to int
ValueError: invalid literal for int() with base 16: ''

```
Any further ideas? (Thanks again for hanging in there with me on this - really appreciated!)

**Comment by Evsdd** [comment]
I can see that it's so very nearly completing successfully, but that weird corrupted, concatenated message is triggering the error.  I'll try and reproduce a similar error and add some further error trapping to the Python code and push an update which hopefully make it more robust.

**Comment by smar000** [comment]
Thanks Dan and yes, it looks as if it is almost there. Maybe worth writing to the file as we go along and get the data for each zone, rather than "all or nothing" in one go at the end?

**Comment by Evsdd** [comment]
I've just pushed an update which adds error trapping to the processing of the message responses which should cope a lot better with the variety of error messages printed to the serial port by the different firmwares for the non-HGI80 devices.  I've been able to test it with a very poorly performing RFBee and it was able to complete 'sucessfully' meaning that an output file is created containing the schedule information for any zones where it was possible to retrieve the full schedule information from the controller.  The code writes the schedule information to the output file zone by zone and if it fails to sucessfully obtain the full schedule information for a zone it moves on to the next.  The output file will only contain the schedule information for those zones which completed successfully.   Note: the code repeats each schedule request 5 times and this is controlled by the line of code: ' if (j == 5): # retry 5 times'.  If you're having trouble successfully obtaining the schedule information you could try increasing the re-try limit to any value you wish which will give it a better chance of completing successfully.

**Comment by smar000** [comment]
Success - I have a local backup!!! Now to test the restore at some point...

Thank you once again for all your help - sincerely appreciated.

**Comment by Evsdd** [comment]
Great.  Thanks for confirming and helping me improve the robustness of the code.  I'll take a look at the restore code too as I'm sure it could benefit from the same error trapping.  If you get the restore working too it's a handy way to make bulk changes to the schedules e.g. to implement additional custom schedules.
